In [1]:
############## PLEASE RUN THIS CELL FIRST! ###################

# import everything and define a test runner function
from importlib import reload
from helper import run
import ecc
import helper

from ecc import FieldElement

In [2]:
from ecc import FieldElement
a = FieldElement(7, 13)
b = FieldElement(6, 13)
print(a == b)
print(a == a)

False
True


### Exercise 1

Write the corresponding method `__ne__` which checks if two `FieldElement` objects are _not equal_ to each other.

#### Make [this test](/edit/code-ch01/ecc.py) pass: `ecc.py:FieldElementTest:test_ne`

In [3]:
# Exercise 1

reload(ecc)
run(ecc.FieldElementTest("test_ne"))

.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK


In [4]:
print(7 % 3)

1


In [5]:
print(-27 % 13)

12


### Exercise 2

Solve these problems in \\(F_{57}\\) (assume all +'s here are \\(+_{f}\\) and -`s here \\(-_{f}\\))

* 44+33
* 9-29
* 17+42+49
* 52-30-38

In [6]:
# Exercise 2

# remember that % is the modulo operator
prime = 57
# 44+33
# 9-29
# 17+42+49
# 52-30-38

In [7]:
(44+33) % prime

20

In [8]:
(9-29) % prime

37

In [9]:
(17+42+49) % prime

51

In [10]:
(52-30-38) % prime

41

In [11]:
from ecc import FieldElement
a = FieldElement(7, 13)
b = FieldElement(12, 13)
c = FieldElement(6, 13)
print(a+b==c)

True


In [12]:
a

FieldElement_13(7)

In [13]:
b

FieldElement_13(12)

In [14]:
a + b

FieldElement_13(6)

### Exercise 3

Write the corresponding `__sub__` method which defines the subtraction of two `FieldElement` objects.

#### Make [this test](/edit/code-ch01/ecc.py) pass: `ecc.py:FieldElementTest:test_sub`

In [15]:
# Exercise 3

reload(ecc)
run(ecc.FieldElementTest("test_sub"))

.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK


### Exercise 4

Solve the following equations in \\(F_{97}\\) (again, assume ⋅ and exponentiation are field versions):

* 95⋅45⋅31
* 17⋅13⋅19⋅44
* \\(12^{7}\\)⋅\\(77^{49}\\)

In [16]:
# Exercise 4

prime = 97

# 95*45*31
# 17*13*19*44
# 12**7*77**49

In [17]:
(95*45*31) % prime

23

In [18]:
(17*13*19*44) % prime

68

In [19]:
(12**7 * 77**49) % prime

63

### Exercise 5

For k = 1, 3, 7, 13, 18, what is this set in \\(F_{19}\\)?

{k⋅0, k⋅1, k⋅2, k⋅3, ... k⋅18}

Do you notice anything about these sets?

In [20]:
# Exercise 5
import numpy as np

prime = 19
fn = np.arange(prime)

for k in [1, 3, 7, 13]:
    print(np.sort((k * fn) % prime))
k = 1  # 3, 7, 13 and 18 are the other possibilities
# loop through all possible k's 0 up to prime-1
# calculate k*iterator % prime

# Hint - sort!

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [21]:
# Exercise 5
import numpy as np

prime = 20
fn = np.arange(prime)

for k in [2, 5, 10, 15, 16, 18, 19]:
    new = np.sort((k * fn) % prime)
    new = np.unique(new)
    print(new, new.size)
k = 1  # 3, 7, 13 and 18 are the other possibilities
# loop through all possible k's 0 up to prime-1
# calculate k*iterator % prime

# Hint - sort!

[ 0  2  4  6  8 10 12 14 16 18] 10
[ 0  5 10 15] 4
[ 0 10] 2
[ 0  5 10 15] 4
[ 0  4  8 12 16] 5
[ 0  2  4  6  8 10 12 14 16 18] 10
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 20


In [22]:
from ecc import FieldElement
a = FieldElement(3, 13)
b = FieldElement(12, 13)
c = FieldElement(10, 13)
print(a*b==c)

True


### Exercise 6

Write the corresponding `__mul__` method which defines the multiplication of two Finite Field elements.

#### Make [this test](/edit/code-ch01/ecc.py) pass: `ecc.py:FieldElementTest:test_mul`

In [23]:
# Exercise 6

reload(ecc)
run(ecc.FieldElementTest("test_mul"))

.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK


In [24]:
from ecc import FieldElement
a = FieldElement(3, 13)
b = FieldElement(1, 13)
print(a**3==b)

True


### Exercise 7

For p = 7, 11, 17, 31, what is this set in \\(F_{p}\\)?

{\\(1^{(p-1)}\\), \\(2^{(p-1)}\\), \\(3^{(p-1)}\\), \\(4^{(p-1)}\\), ... \\((p-1)^{(p-1)}\\)}

In [25]:
# Exercise 7

primes = [7, 11, 17, 31, 43]



In [26]:
import numpy as np

p = 11

ori = np.arange(1, p)
for i in ori:
    print((i**(p-1)) % p)
    #print(f"({i} ** {p-1}) % p = {t}")

1
1
1
1
1
1
1
1
8
4


> 上面出现 8 和 4 是因为整型溢出的问题。numpy 的整型默认为 int32，当幂指数过大时会溢出。而 python 自带的 range 没有整型上界的规定。

In [34]:
type(ori[0])

numpy.int32

In [27]:
(i**(p-1)) % p

4

In [28]:
i = 10
p = 11
(i**(p-1)) % p

1

In [29]:
(10**10) % 11

1

In [30]:
for i in range(1, 11):
    print((i**(p-1)) % p)

1
1
1
1
1
1
1
1
1
1


In [31]:
(10 ** 10) % 11

1

In [32]:
for prime in (7, 11, 17, 31, 43):
    print([pow(i, prime-1, prime) for i in range(1, prime)])

[1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


### Exercise 8

Solve the following equations in \\(F_{31}\\):

* 3 / 24
* \\(17^{-3}\\)
* \\(4^{-4}\\)⋅11

In [35]:
# Exercise 8

# 3/24
3 * pow(24, 29, 31) % 31

4

In [36]:
3 * pow(24, 29) % 31

4

In [39]:
# 17**-3
1 * pow(17, 29*3, 31) % 31

29

In [41]:
# 4**-4*11

11 * pow(4, 29*4, 31) % 31

13

### Exercise 9

Write the corresponding `__truediv__` method which defines the division of two field elements.

Note that in Python3, division is separated into `__truediv__` and `__floordiv__`. The first does normal division, the second does integer division.

#### Make [this test](/edit/code-ch01/ecc.py) pass: `ecc.py:FieldElementTest:test_div`

In [50]:
# Exercise 9

reload(ecc)
run(ecc.FieldElementTest("test_div"))

.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK


In [51]:
from ecc import FieldElement
a = FieldElement(7, 13)
b = FieldElement(8, 13)
print(a**-3==b)

True


In [44]:
a / b

FieldElement_13(9)

In [45]:
7 * pow(8, 11, 13) % 13

9